version: 2
builds:
  - id: obsidian-cli
    binary: obsidian-cli
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: obsidian-cli
    homepage: https://github.com/Yakitrak/obsidian-cli
    repository:
      owner: Yakitrak
      name: homebrew-yakitrak
    commit_author:
      name: kartikayjainwal
      email: kartikayjainwal@gmail.com

scoops:
  - name: obsidian-cli
    homepage: https://github.com/Yakitrak/obsidian-cli
    repository:
      owner: Yakitrak
      name: scoop-yakitrak
    commit_author:
      name: kartikayjainwal
      email: kartikayjainwal@gmail.com

aurs:
  - name: obsidian-cli-bin
    homepage: https://github.com/Yakitrak/obsidian-cli
    description: Interact with Obsidian in the terminal. Open, search, create, update and move notes!
    maintainers:
      - 'Kartikay Jainwal <kartikayjainwal at gmail dot com>'
      - 'Jonathan Neidel <aur at jneidel dot com>'
    license: 'MIT'
    private_key: '{{ .Env.AUR_KEY }}'
    git_url: 'ssh://aur@aur.archlinux.org/obsidian-cli-bin.git'
    package: |-
      install -Dm755 "./obsidian-cli" "${pkgdir}/usr/bin/obsidian-cli"
      ./obsidian-cli completion bash >obsidian-cli.bash
      ./obsidian-cli completion fish >obsidian-cli.fish
      ./obsidian-cli completion zsh >_obsidian-cli
      install -Dm644 obsidian-cli.bash "${pkgdir}/usr/share/bash-completion/completions/obsidian-cli"
      install -Dm644 obsidian-cli.fish "${pkgdir}/usr/share/fish/completions/obsidian-cli.fish"
      install -Dm644 _obsidian-cli "${pkgdir}/usr/share/zsh/site-functions/_obsidian-cli"


checksum:
  name_template: "checksums.txt"
