version: 2
builds:
  - id: obsidian-cli
    binary: obsidian-cli
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: obsidian-cli
    homepage: https://github.com/atomicobject/obsidian-cli
    repository:
      owner: atomicobject
      name: homebrew-obsidian-cli
    # commit_author:
    #   name: your-name
    #   email: your-email@atomicobject.com

checksum:
  name_template: "checksums.txt"
