package obsidian

import "strings"

var defaultIgnorePatterns = []string{
	".git/",
	".github/",
	".idea/",
	".vscode/",
	".cursor/",
	".codex/",
	".cache/",
	".claude/",
	".DS_Store",
	"node_modules/",
	"vendor/",
	"dist/",
	"build/",
	"out/",
	"tmp/",
	"temp/",
	"venv/",
	".venv/",
	".pytest_cache/",
	".mypy_cache/",
	".ruff_cache/",
	"coverage/",
	"coverage.out",
	"target/",
	"bin/",
}

// DefaultIgnorePatterns returns a copy of the built-in ignore prefixes.
func DefaultIgnorePatterns() []string {
	out := make([]string, len(defaultIgnorePatterns))
	copy(out, defaultIgnorePatterns)
	return out
}

// DefaultIgnoreFile renders a .obsidianignore body using the default patterns.
func DefaultIgnoreFile() string {
	var b strings.Builder
	b.WriteString("# Default .obsidianignore generated by obsidian-cli\n")
	b.WriteString("# Remove entries you want to include in indexing/search\n")
	b.WriteString("# Hidden entries (e.g., .git) are ignored automatically\n")
	for _, p := range defaultIgnorePatterns {
		b.WriteString(p)
		if !strings.HasSuffix(p, "\n") {
			b.WriteString("\n")
		}
	}
	return b.String()
}
